#!/bin/bash
FILES="test1.bin
test2.bin
test3.bin
pan-tadeusz-czyli-ostatni-zajazd-na-litwie.txt"

CODES="--omega
--gamma
--delta
--fib"

total=0
passed=0

for f in $FILES
do
    for c in $CODES
    do
        echo -e "\nTESTING: $f"
        python3 lzw.py --encode $f encoded $c
        python3 lzw.py --decode encoded decoded $c
        fileSum=$(shasum -a 512 $f | cut -c1-128) 
        outSum=$(shasum -a 512 decoded | cut -c1-128) 
        if [ "$fileSum" = "$outSum" ]; then
            echo "TEST PASSED"
            ((passed++))
        else
            echo "TEST FAILED"
        fi
        ((total++))
    done
done

echo -e "\nPASSED: $passed/$total"